import { Injectable } from '@nestjs/common';

export interface GallerySampleSummary {
  id: string;
  name: string;
  description: string;
  moduleCount: number;
  cycleCount: number;
}

@Injectable()
export class GalleryIndexBuilder {
  /** Builds a static, dependency-free index.html linking to each sample's generated diagram + explanation. */
  build(summaries: GallerySampleSummary[]): string {
    const cards = summaries.map((summary) => this.renderCard(summary)).join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>arch-lens sample gallery</title>
<style>
${this.stylesheet()}
</style>
</head>
<body>
<header>
  <h1>arch-lens sample gallery</h1>
  <p>Diagrams and explanations generated by arch-lens against a handful of small sample repos.</p>
</header>
<main>
${cards}
</main>
</body>
</html>
`;
  }

  private renderCard(summary: GallerySampleSummary): string {
    const cycleNote =
      summary.cycleCount > 0
        ? `${summary.cycleCount} cycle${summary.cycleCount === 1 ? '' : 's'} found`
        : 'no cycles';

    return `  <article class="card">
    <h2>${this.escape(summary.name)}</h2>
    <p class="description">${this.escape(summary.description)}</p>
    <p class="stats">${summary.moduleCount} module(s) &middot; ${cycleNote}</p>
    <ul class="links">
      <li><a href="./${summary.id}/diagram.html">Interactive diagram</a></li>
      <li><a href="./${summary.id}/diagram.mmd">Mermaid source</a></li>
      <li><a href="./${summary.id}/explanation.md">Explanation</a></li>
    </ul>
  </article>`;
  }

  private stylesheet(): string {
    return `  html, body { margin: 0; font-family: sans-serif; background: #1e1e2e; color: #cdd6f4; }
  header { padding: 32px 24px 8px; }
  header p { color: #a6adc8; }
  main { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; padding: 8px 24px 32px; }
  .card { background: #313244; border: 1px solid #45475a; border-radius: 8px; padding: 16px 20px; }
  .card h2 { margin: 0 0 8px; font-size: 18px; }
  .description { color: #bac2de; font-size: 14px; }
  .stats { color: #94e2d5; font-size: 13px; }
  .links { list-style: none; padding: 0; margin: 8px 0 0; }
  .links li { margin: 4px 0; }
  a { color: #89b4fa; }`;
  }

  private escape(value: string): string {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
}
